### ISSUE TITLE
可以增加 ipv6 么?

### ISSUE THREAD

**Issue by flingflingfling** [zhengxiaowai/tcping#5]
一直用大佬的 tcping 版本 , 不知道能不能增加 ipv6 的 tcp ping 功能 . 
毕竟直接用 pip3 install tcping 太方便了 .

**Comment by soloopooo** [comment]
![图片](https://user-images.githubusercontent.com/36123081/210728931-c43bdb8e-4151-47cb-b85e-3cd114781df8.png)
![图片](https://user-images.githubusercontent.com/36123081/210729004-471ccedf-8f83-40a9-9167-4c40ae9dce0c.png)

ipv6的支持可以修改这里。

**Comment by flingflingfling** [comment]
> 

谢谢！

**Comment by duzhuoshanwai** [comment]
> ![图片](https://user-images.githubusercontent.com/36123081/210728931-c43bdb8e-4151-47cb-b85e-3cd114781df8.png) ![图片](https://user-images.githubusercontent.com/36123081/210729004-471ccedf-8f83-40a9-9167-4c40ae9dce0c.png)
> 
> ipv6的支持可以修改这里。
```
s = (
    self._create_socket(socket.AF_INET6, socket.SOCK_STREAM)
    if ipv6
    else self._create_socket(socket.AF_INET, socket.SOCK_STREAM)
)
 ```
```
@click.option("--ipv6", "-6", is_flag=True, help="ipv6")
```
```
def cli(host, port, count, timeout, report, ipv6):
    ping = Ping(host, port, timeout)
    try:
        ping.ping(count, ipv6=ipv6)  # Pass the ipv6 argument to the ping method
    except KeyboardInterrupt:
        pass

    if report:
        iprint(ping.result.table)
    else:
        iprint(ping.result.raw)
    sys.exit(ping.status)
```
